apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  imagePullSecrets:
  - name: credentials
  containers:
  - name: mysql
    image: 851725639640.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_ROOT_PASSWORD
