apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  imagePullSecrets:
  - name: credentials
  containers:
  - name: webapp
    image: 851725639640.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp
    ports:
    - containerPort: 8080
