apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
      - name: credentials
      containers:
      - name: webapp
        image: 851725639640.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DBHOST
        - name: DBPORT
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DBPORT
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DBPWD
